"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Check, Copy, Download, KeyRound, Loader2, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createKeyAction } from "./actions";

// CopyBlock: one tab inside the success dialog. Auto-copies on mount so the
// user always lands with the key in their clipboard before they even click —
// then offers a big visible Copy button + click-to-select on the code itself
// for cases where the clipboard API is blocked.
function CopyBlock({ value, autoCopy }: { value: string; autoCopy: boolean }) {
  const [copied, setCopied] = useState(false);
  const codeRef = useRef<HTMLElement>(null);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API blocked — auto-select the code instead and tell the user.
      if (codeRef.current) {
        const r = document.createRange();
        r.selectNodeContents(codeRef.current);
        const sel = window.getSelection();
        sel?.removeAllRanges();
        sel?.addRange(r);
      }
      toast.message("Clipboard blocked — text selected, press ⌘C");
    }
  };

  // Pre-copy on mount so the value is ALREADY in the user's clipboard when the
  // dialog renders. Surprising but safe — the only thing it overwrites is
  // whatever the user copied to open the dialog, and we toast to confirm.
  useEffect(() => {
    if (!autoCopy) return;
    navigator.clipboard.writeText(value).then(
      () => {
        setCopied(true);
        toast.success("Key auto-copied — paste it now");
        setTimeout(() => setCopied(false), 2500);
      },
      () => {},
    );
  }, [autoCopy, value]);

  return (
    <div className="space-y-2">
      <code
        ref={codeRef}
        className="block cursor-text select-all break-all rounded-md border bg-background px-4 py-3 font-mono text-sm leading-relaxed"
        onClick={() => {
          if (codeRef.current) {
            const r = document.createRange();
            r.selectNodeContents(codeRef.current);
            const sel = window.getSelection();
            sel?.removeAllRanges();
            sel?.addRange(r);
          }
        }}
      >
        {value}
      </code>
      <Button type="button" className="w-full" variant={copied ? "secondary" : "default"} onClick={copy}>
        {copied ? <Check className="text-green-600" /> : <Copy />}
        {copied ? "Copied — paste it somewhere safe NOW" : "Copy"}
      </Button>
    </div>
  );
}

export function CreateKeyDialog({ projectId }: { projectId: string }) {
  const [open, setOpen] = useState(false);
  const [pending, start] = useTransition();
  const [created, setCreated] = useState<string | null>(null);
  const [confirmedSaved, setConfirmedSaved] = useState(false);
  const router = useRouter();

  // Generates a downloadable .env snippet so users who'd rather save than
  // copy get a file with the right shape.
  const downloadEnv = () => {
    if (!created) return;
    const body = `# Generated by EchoProxy dashboard. Source this from your service .env.\n` +
      `ECHOPROXY_API_KEY=${created}\n` +
      `ECHOPROXY_ENDPOINT=https://ingest-track.sidcorp.co\n` +
      `ECHOPROXY_PROXY_URL=https://proxy-track.sidcorp.co\n`;
    const blob = new Blob([body], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `echoproxy-${created.slice(0, 12)}.env`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(".env downloaded");
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(v) => {
        // Block accidental close if the user hasn't confirmed saving the key.
        if (!v && created && !confirmedSaved) {
          toast.error("Confirm you've saved the key before closing");
          return;
        }
        setOpen(v);
        if (!v) {
          setCreated(null);
          setConfirmedSaved(false);
          if (created) router.refresh();
        }
      }}
    >
      <DialogTrigger asChild>
        <Button>
          <Plus /> New API key
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl">
        {created ? (
          <>
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <KeyRound className="h-5 w-5 text-success" /> API key created — save it now
              </DialogTitle>
              <DialogDescription>
                This is the only time you&apos;ll see the full key. We auto-copied it to your clipboard; pick a format below if you need something else.
              </DialogDescription>
            </DialogHeader>

            <div className="my-2 flex items-center gap-2 rounded-md border border-destructive/40 bg-destructive/5 px-3 py-2 text-xs font-medium text-destructive">
              <AlertTriangle className="h-4 w-4" />
              We store only a hash of this key. If you lose it, you must revoke + recreate.
            </div>

            <Tabs defaultValue="raw" className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="raw">Raw key</TabsTrigger>
                <TabsTrigger value="env">.env line</TabsTrigger>
                <TabsTrigger value="curl">curl example</TabsTrigger>
              </TabsList>

              <TabsContent value="raw" className="pt-3">
                <CopyBlock value={created} autoCopy />
              </TabsContent>

              <TabsContent value="env" className="pt-3 space-y-2">
                <p className="text-xs text-muted-foreground">
                  Paste these 3 lines into your service&apos;s <code className="font-mono">.env</code>.
                </p>
                <CopyBlock
                  autoCopy={false}
                  value={`ECHOPROXY_API_KEY=${created}\nECHOPROXY_ENDPOINT=https://ingest-track.sidcorp.co\nECHOPROXY_PROXY_URL=https://proxy-track.sidcorp.co`}
                />
                <Button variant="outline" size="sm" type="button" onClick={downloadEnv}>
                  <Download /> Download .env file
                </Button>
              </TabsContent>

              <TabsContent value="curl" className="pt-3 space-y-2">
                <p className="text-xs text-muted-foreground">
                  Drop-in curl that goes through proxy-track and proxies to httpbin.org. Replace the target with whatever upstream you need.
                </p>
                <CopyBlock
                  autoCopy={false}
                  value={`curl -i https://proxy-track.sidcorp.co/get \\\n  -H "X-Echo-Key: ${created}" \\\n  -H "X-Echo-Target: https://httpbin.org"`}
                />
              </TabsContent>
            </Tabs>

            <div className="flex items-start gap-2 rounded-md border bg-muted/30 p-3 text-sm">
              <input
                id="confirm-saved"
                type="checkbox"
                className="mt-1 h-4 w-4 cursor-pointer"
                checked={confirmedSaved}
                onChange={(e) => setConfirmedSaved(e.target.checked)}
              />
              <Label htmlFor="confirm-saved" className="cursor-pointer text-sm font-normal">
                I&apos;ve saved this key somewhere safe (clipboard, password manager, secret store).
              </Label>
            </div>

            <DialogFooter>
              <Button onClick={() => setOpen(false)} disabled={!confirmedSaved}>
                Done
              </Button>
            </DialogFooter>
          </>
        ) : (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              const fd = new FormData(e.currentTarget);
              start(async () => {
                const res = await createKeyAction(projectId, null, fd);
                if (!res.ok) {
                  toast.error(res.error || "Failed to create key");
                  return;
                }
                setCreated(res.raw ?? null);
                toast.success("API key created");
              });
            }}
          >
            <DialogHeader>
              <DialogTitle>New API key</DialogTitle>
              <DialogDescription>
                Configure the upstream allowlist and body capture limit. Both can be left empty to use sane defaults.
              </DialogDescription>
            </DialogHeader>
            <div className="my-4 space-y-4">
              <div className="space-y-2">
                <Label htmlFor="description">Description</Label>
                <Input
                  id="description"
                  name="description"
                  placeholder="Production checkout API"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="allowlist">Allowlist (comma-separated hostnames)</Label>
                <Textarea
                  id="allowlist"
                  name="allowlist"
                  placeholder="api.example.com, api.payments.example.com"
                  rows={2}
                />
                <p className="text-xs text-muted-foreground">
                  Empty = allow all hosts. Recommended for production: list every upstream the key may forward to.
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="body_cap">Body capture cap (bytes)</Label>
                <Input id="body_cap" name="body_cap" type="number" min={0} placeholder="65536" />
                <p className="text-xs text-muted-foreground">
                  0 (or empty) = use the proxy default of 64 KB.
                </p>
              </div>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" disabled={pending}>
                {pending && <Loader2 className="animate-spin" />}
                Create key
              </Button>
            </DialogFooter>
          </form>
        )}
      </DialogContent>
    </Dialog>
  );
}
