// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: event.proto

// Public contract between echoproxy platform and every language SDK.
// Backwards-compatible only. See .claude/skills/echoproxy-event-schema/SKILL.md.

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngest_Ingest_FullMethodName       = "/echoproxy.v1.EventIngest/Ingest"
	EventIngest_IngestStream_FullMethodName = "/echoproxy.v1.EventIngest/IngestStream"
)

// EventIngestClient is the client API for EventIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngestClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error)
}

type eventIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestClient(cc grpc.ClientConnInterface) EventIngestClient {
	return &eventIngestClient{cc}
}

func (c *eventIngestClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, EventIngest_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IngestRequest, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngest_ServiceDesc.Streams[0], EventIngest_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IngestRequest, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngest_IngestStreamClient = grpc.BidiStreamingClient[IngestRequest, IngestResponse]

// EventIngestServer is the server API for EventIngest service.
// All implementations must embed UnimplementedEventIngestServer
// for forward compatibility.
type EventIngestServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	IngestStream(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error
	mustEmbedUnimplementedEventIngestServer()
}

// UnimplementedEventIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestServer struct{}

func (UnimplementedEventIngestServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedEventIngestServer) IngestStream(grpc.BidiStreamingServer[IngestRequest, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedEventIngestServer) mustEmbedUnimplementedEventIngestServer() {}
func (UnimplementedEventIngestServer) testEmbeddedByValue()                     {}

// UnsafeEventIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestServer will
// result in compilation errors.
type UnsafeEventIngestServer interface {
	mustEmbedUnimplementedEventIngestServer()
}

func RegisterEventIngestServer(s grpc.ServiceRegistrar, srv EventIngestServer) {
	// If the following call panics, it indicates UnimplementedEventIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngest_ServiceDesc, srv)
}

func _EventIngest_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngest_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngest_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestServer).IngestStream(&grpc.GenericServerStream[IngestRequest, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngest_IngestStreamServer = grpc.BidiStreamingServer[IngestRequest, IngestResponse]

// EventIngest_ServiceDesc is the grpc.ServiceDesc for EventIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echoproxy.v1.EventIngest",
	HandlerType: (*EventIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _EventIngest_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _EventIngest_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "event.proto",
}
