// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: event.proto

// Public contract between echoproxy platform and every language SDK.
// Backwards-compatible only. See .claude/skills/echoproxy-event-schema/SKILL.md.

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	EventId     string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`              // ULID, idempotency key
	TimestampNs int64  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // capture time (producer clock)
	Source      string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                               // "proxy" | "sdk-laravel" | "sdk-python" | "sdk-go" | ...
	SdkVersion  string `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	ProjectId   uint64 `protobuf:"varint,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ApiKeyId    uint64 `protobuf:"varint,6,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	// HTTP envelope
	Method            string            `protobuf:"bytes,10,opt,name=method,proto3" json:"method,omitempty"`
	Scheme            string            `protobuf:"bytes,11,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Host              string            `protobuf:"bytes,12,opt,name=host,proto3" json:"host,omitempty"`
	Path              string            `protobuf:"bytes,13,opt,name=path,proto3" json:"path,omitempty"`
	Query             string            `protobuf:"bytes,14,opt,name=query,proto3" json:"query,omitempty"`
	Status            uint32            `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs         uint32            `protobuf:"varint,16,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // total: arrival → response fully sent to client
	ReqSize           uint32            `protobuf:"varint,17,opt,name=req_size,json=reqSize,proto3" json:"req_size,omitempty"`
	ResSize           uint32            `protobuf:"varint,18,opt,name=res_size,json=resSize,proto3" json:"res_size,omitempty"`
	UpstreamLatencyMs uint32            `protobuf:"varint,19,opt,name=upstream_latency_ms,json=upstreamLatencyMs,proto3" json:"upstream_latency_ms,omitempty"` // upstream RoundTrip duration (request sent → response received)
	UpstreamTtfbMs    uint32            `protobuf:"varint,26,opt,name=upstream_ttfb_ms,json=upstreamTtfbMs,proto3" json:"upstream_ttfb_ms,omitempty"`          // upstream time-to-first-byte (request sent → first response byte)
	ReqHeaders        map[string]string `protobuf:"bytes,20,rep,name=req_headers,json=reqHeaders,proto3" json:"req_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResHeaders        map[string]string `protobuf:"bytes,21,rep,name=res_headers,json=resHeaders,proto3" json:"res_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReqBody           []byte            `protobuf:"bytes,22,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	ResBody           []byte            `protobuf:"bytes,23,opt,name=res_body,json=resBody,proto3" json:"res_body,omitempty"`
	ReqBodyTruncated  bool              `protobuf:"varint,24,opt,name=req_body_truncated,json=reqBodyTruncated,proto3" json:"req_body_truncated,omitempty"`
	ResBodyTruncated  bool              `protobuf:"varint,25,opt,name=res_body_truncated,json=resBodyTruncated,proto3" json:"res_body_truncated,omitempty"`
	// Network / context
	ClientIp      string            `protobuf:"bytes,30,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string            `protobuf:"bytes,31,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	TraceId       string            `protobuf:"bytes,32,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // W3C traceparent
	Attributes    map[string]string `protobuf:"bytes,33,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string            `protobuf:"bytes,34,opt,name=error,proto3" json:"error,omitempty"`         // non-empty if upstream failed
	Direction     string            `protobuf:"bytes,35,opt,name=direction,proto3" json:"direction,omitempty"` // "inbound" (server middleware) | "outbound" (proxy / client wrapper)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpEvent) Reset() {
	*x = HttpEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpEvent) ProtoMessage() {}

func (x *HttpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpEvent.ProtoReflect.Descriptor instead.
func (*HttpEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *HttpEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *HttpEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *HttpEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HttpEvent) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *HttpEvent) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *HttpEvent) GetApiKeyId() uint64 {
	if x != nil {
		return x.ApiKeyId
	}
	return 0
}

func (x *HttpEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpEvent) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpEvent) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HttpEvent) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpEvent) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HttpEvent) GetReqSize() uint32 {
	if x != nil {
		return x.ReqSize
	}
	return 0
}

func (x *HttpEvent) GetResSize() uint32 {
	if x != nil {
		return x.ResSize
	}
	return 0
}

func (x *HttpEvent) GetUpstreamLatencyMs() uint32 {
	if x != nil {
		return x.UpstreamLatencyMs
	}
	return 0
}

func (x *HttpEvent) GetUpstreamTtfbMs() uint32 {
	if x != nil {
		return x.UpstreamTtfbMs
	}
	return 0
}

func (x *HttpEvent) GetReqHeaders() map[string]string {
	if x != nil {
		return x.ReqHeaders
	}
	return nil
}

func (x *HttpEvent) GetResHeaders() map[string]string {
	if x != nil {
		return x.ResHeaders
	}
	return nil
}

func (x *HttpEvent) GetReqBody() []byte {
	if x != nil {
		return x.ReqBody
	}
	return nil
}

func (x *HttpEvent) GetResBody() []byte {
	if x != nil {
		return x.ResBody
	}
	return nil
}

func (x *HttpEvent) GetReqBodyTruncated() bool {
	if x != nil {
		return x.ReqBodyTruncated
	}
	return false
}

func (x *HttpEvent) GetResBodyTruncated() bool {
	if x != nil {
		return x.ResBodyTruncated
	}
	return false
}

func (x *HttpEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *HttpEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *HttpEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HttpEvent) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HttpEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HttpEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*HttpEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *IngestRequest) GetEvents() []*HttpEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      uint32                 `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetRejected() uint32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\fechoproxy.v1\"\xab\t\n" +
	"\tHttpEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\x04R\tprojectId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x06 \x01(\x04R\bapiKeyId\x12\x16\n" +
	"\x06method\x18\n" +
	" \x01(\tR\x06method\x12\x16\n" +
	"\x06scheme\x18\v \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\f \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\r \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x0e \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x0f \x01(\rR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x10 \x01(\rR\tlatencyMs\x12\x19\n" +
	"\breq_size\x18\x11 \x01(\rR\areqSize\x12\x19\n" +
	"\bres_size\x18\x12 \x01(\rR\aresSize\x12.\n" +
	"\x13upstream_latency_ms\x18\x13 \x01(\rR\x11upstreamLatencyMs\x12(\n" +
	"\x10upstream_ttfb_ms\x18\x1a \x01(\rR\x0eupstreamTtfbMs\x12H\n" +
	"\vreq_headers\x18\x14 \x03(\v2'.echoproxy.v1.HttpEvent.ReqHeadersEntryR\n" +
	"reqHeaders\x12H\n" +
	"\vres_headers\x18\x15 \x03(\v2'.echoproxy.v1.HttpEvent.ResHeadersEntryR\n" +
	"resHeaders\x12\x19\n" +
	"\breq_body\x18\x16 \x01(\fR\areqBody\x12\x19\n" +
	"\bres_body\x18\x17 \x01(\fR\aresBody\x12,\n" +
	"\x12req_body_truncated\x18\x18 \x01(\bR\x10reqBodyTruncated\x12,\n" +
	"\x12res_body_truncated\x18\x19 \x01(\bR\x10resBodyTruncated\x12\x1b\n" +
	"\tclient_ip\x18\x1e \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x1f \x01(\tR\tuserAgent\x12\x19\n" +
	"\btrace_id\x18  \x01(\tR\atraceId\x12G\n" +
	"\n" +
	"attributes\x18! \x03(\v2'.echoproxy.v1.HttpEvent.AttributesEntryR\n" +
	"attributes\x12\x14\n" +
	"\x05error\x18\" \x01(\tR\x05error\x12\x1c\n" +
	"\tdirection\x18# \x01(\tR\tdirection\x1a=\n" +
	"\x0fReqHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fResHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\rIngestRequest\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.echoproxy.v1.HttpEventR\x06events\"`\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\rR\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\rR\brejected\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xa1\x01\n" +
	"\vEventIngest\x12C\n" +
	"\x06Ingest\x12\x1b.echoproxy.v1.IngestRequest\x1a\x1c.echoproxy.v1.IngestResponse\x12M\n" +
	"\fIngestStream\x12\x1b.echoproxy.v1.IngestRequest\x1a\x1c.echoproxy.v1.IngestResponse(\x010\x01B/Z-github.com/songhieu/EchoProxy/pkg/event;eventb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_event_proto_goTypes = []any{
	(*HttpEvent)(nil),      // 0: echoproxy.v1.HttpEvent
	(*IngestRequest)(nil),  // 1: echoproxy.v1.IngestRequest
	(*IngestResponse)(nil), // 2: echoproxy.v1.IngestResponse
	nil,                    // 3: echoproxy.v1.HttpEvent.ReqHeadersEntry
	nil,                    // 4: echoproxy.v1.HttpEvent.ResHeadersEntry
	nil,                    // 5: echoproxy.v1.HttpEvent.AttributesEntry
}
var file_event_proto_depIdxs = []int32{
	3, // 0: echoproxy.v1.HttpEvent.req_headers:type_name -> echoproxy.v1.HttpEvent.ReqHeadersEntry
	4, // 1: echoproxy.v1.HttpEvent.res_headers:type_name -> echoproxy.v1.HttpEvent.ResHeadersEntry
	5, // 2: echoproxy.v1.HttpEvent.attributes:type_name -> echoproxy.v1.HttpEvent.AttributesEntry
	0, // 3: echoproxy.v1.IngestRequest.events:type_name -> echoproxy.v1.HttpEvent
	1, // 4: echoproxy.v1.EventIngest.Ingest:input_type -> echoproxy.v1.IngestRequest
	1, // 5: echoproxy.v1.EventIngest.IngestStream:input_type -> echoproxy.v1.IngestRequest
	2, // 6: echoproxy.v1.EventIngest.Ingest:output_type -> echoproxy.v1.IngestResponse
	2, // 7: echoproxy.v1.EventIngest.IngestStream:output_type -> echoproxy.v1.IngestResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
