// Package event holds the public event schema (generated by protoc) plus a
// thin producer wrapper used by every event-emitting service.
package event

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/twmb/franz-go/pkg/kgo"
	"google.golang.org/protobuf/proto"
)

// Producer is a thin wrapper around franz-go tuned for low-latency
// fire-and-forget event production.
type Producer struct {
	client *kgo.Client
	topic  string
}

// ProducerConfig holds the knobs we expose from franz-go.
type ProducerConfig struct {
	Brokers       []string
	Topic         string
	LingerMs      int
	MaxBuffered   int
	ClientID      string
	RequiredAcks  string // "leader" (default) | "all" | "none"
}

// NewProducer constructs and pings a Kafka producer. Callers should `defer p.Close()`.
func NewProducer(cfg ProducerConfig) (*Producer, error) {
	if cfg.LingerMs <= 0 {
		cfg.LingerMs = 5
	}
	if cfg.MaxBuffered <= 0 {
		cfg.MaxBuffered = 1_000_000
	}
	if cfg.ClientID == "" {
		cfg.ClientID = "echoproxy"
	}
	acks := kgo.LeaderAck()
	switch cfg.RequiredAcks {
	case "all":
		acks = kgo.AllISRAcks()
	case "none":
		acks = kgo.NoAck()
	}

	opts := []kgo.Opt{
		kgo.SeedBrokers(cfg.Brokers...),
		kgo.ClientID(cfg.ClientID),
		kgo.ProducerLinger(time.Duration(cfg.LingerMs) * time.Millisecond),
		kgo.ProducerBatchCompression(kgo.ZstdCompression()),
		kgo.RequiredAcks(acks),
		kgo.MaxBufferedRecords(cfg.MaxBuffered),
		kgo.RecordPartitioner(kgo.StickyKeyPartitioner(nil)),
		kgo.AllowAutoTopicCreation(),
	}
	// franz-go enables idempotent writes by default, which requires acks=all.
	// We trade idempotency for the lower-latency leader-ack mode (log data is
	// fine with at-least-once semantics).
	if cfg.RequiredAcks != "all" {
		opts = append(opts, kgo.DisableIdempotentWrite())
	}
	cl, err := kgo.NewClient(opts...)
	if err != nil {
		return nil, fmt.Errorf("kafka new client: %w", err)
	}
	return &Producer{client: cl, topic: cfg.Topic}, nil
}

// Ping verifies the producer can reach the cluster.
func (p *Producer) Ping(ctx context.Context) error {
	if err := p.client.Ping(ctx); err != nil {
		return fmt.Errorf("kafka ping: %w", err)
	}
	return nil
}

// Produce serialises the event and enqueues it. Non-blocking on the producer
// internal queue (franz-go has its own backpressure when MaxBufferedRecords
// is hit; in that case `cb` is invoked with an error).
func (p *Producer) Produce(ctx context.Context, ev *HttpEvent, cb func(err error)) {
	data, err := proto.Marshal(ev)
	if err != nil {
		if cb != nil {
			cb(fmt.Errorf("marshal: %w", err))
		}
		return
	}
	rec := &kgo.Record{
		Topic: p.topic,
		Key:   []byte(strconv.FormatUint(ev.ApiKeyId, 10)),
		Value: data,
	}
	p.client.Produce(ctx, rec, func(_ *kgo.Record, err error) {
		if cb != nil {
			cb(err)
		}
	})
}

// Flush waits for all in-flight records or returns when ctx is done.
func (p *Producer) Flush(ctx context.Context) error {
	return p.client.Flush(ctx)
}

// Close shuts down the underlying client.
func (p *Producer) Close() {
	p.client.Close()
}
