{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "echoproxy.fullname" . }}-secrets
  labels:
    {{- include "echoproxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_BROKERS:    {{ .Values.secrets.kafkaBrokers   | quote }}
  CLICKHOUSE_DSN:   {{ .Values.secrets.clickhouseDSN  | quote }}
  POSTGRES_DSN:     {{ .Values.secrets.postgresDSN    | quote }}
  REDIS_ADDR:       {{ .Values.secrets.redisAddr      | quote }}
  JWT_SECRET:       {{ .Values.secrets.jwtSecret      | quote }}
  NEXTAUTH_SECRET:  {{ .Values.dashboard.nextauthSecret | quote }}
{{- end }}
